name: Terraform CI/CD

on:
  push:
    paths:
      - 'infrastructure/**'
      - 'infra-cicd.yml'
    branches:
      - main
      
jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID2 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY2 }}
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.3
        
      - name: Terraform Init
        run: terraform init
        working-directory: infrastructure

      - name: Terraform Validate
        run: terraform validate
        working-directory: infrastructure

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: infrastructure


